import { color } from './generales';
  import {type option} from '@/types/generales'
  export interface EconomicoForm {
    id?:number,
    economico: string,
    placas: string,
    vin: string,
    anio:number|"",
    marca:string,
    modelo:string,
    color:string,
    tipo_id: number|null
  }
  export interface OrdenServicioForm {
    id?:number,
    orden_seguimiento: string,
    orden_opcional: string,
    ubicacion: string,
    tipo_presupuesto_id: number
    modulo_orden_id: number,
    vehiculo_concepto_id: number | string | undefined,
    empresa_id: number | string | undefined,
    cliente_id:number | string | undefined,
    vehiculo_id: number | string | undefined,
    telefono: number,
    estimacion: Date,
    kilometraje: number,
    gasolina: number,
    administrador: string,
    jefe: string,
    trabajador: string,
    tecnico: string,
    indicaciones_cliente: string,
    descripcion_mo: string,
    inventario:InventarioForm,
    pintura:PinturaForm,
    condiciones_interiores:CondicionesInterioresForm,
    condiciones_exteriores:CondicionesExterioresForm,
    imagenes_evidencia:File[],
    carro:File|null,
    firma:File|null,
    cambiar_archivos: boolean,
  }
  export interface DetallesGeneralesBaseProps {
    id?:number
    orden_seguimiento: string,
    orden_opcional: string,
    ubicacion: string,
    tipo_id: 5|6|7
    modulo_orden: number|string,
    vehiculo: option| null,
    vehiculo_concepto_id: option| null,
    empresa:option|null,
    cliente:option|null,
    telefono: number | null,
    estimacion: Date,
    kilometraje: number | null,
    gasolina: number | string,
    administrador: string,
    jefe: string,
    trabajador: string,
    tecnico: string,
    indicaciones_cliente: string,
    descripcion_mo: string,
    cambiar_archivos: boolean,
  }
  export interface FilesForm {
    file:File,
    tipo_id:number
  }
  export interface PinturaForm{
    decolorada:boolean,
    color_desigual:boolean,
    rayones:boolean,
    grietas:boolean,
    golpes:boolean,
    emblemas:boolean,
    logos:boolean,
    rociado:boolean,
    granizo:boolean,
    lluvia:boolean,
  }
  export interface InventarioForm{
    llanta:boolean,
    cables:boolean,
    estuche:boolean,
    llave_tuerca:boolean,
    triangulo:boolean,
    tarjeta_circulacion:boolean,
    cubreruedas:boolean,
    candado_rueda:boolean,
    extinguidor:boolean,
    gato:boolean,
    placas:boolean,
  }
  export interface CondicionesInterioresForm{
    puerta_izq_f:string,
    puerta_izq_t:string,
    puerta_der_f:string,
    puerta_der_t:string,
    asiento_izq_f:string,
    asiento_izq_t:string,
    asiento_der_f:string,
    asiento_der_t:string,
    consola:string,
    claxon:string,
    tablero:string,
    quemacocos:string,
    toldo:string,
    elevadores:string,
    luces:string,
    seguros:string,
    climatizador:string,
    radio:string,
    retrovisor:string,
    tapetes:string,
  }
  export interface CondicionesExterioresForm{
    antena_radio:string,
    estribos:string,
    antena_telefono:string,
    guardafangos:string,
    antena_cb:string,
    parabrisas:string,
    alarma:string,
    limpiaparabrisas:string,
    luces:string,
    espejos_laterales:string
  }